### ISSUE TITLE
Milford chem June21

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#1]
- [x] Find out about 3 samples that may not have been run from 2018.05.18
- [ ] Match results with experiment/pH/temp/salinity

_markings on the bottle will give the record of the set points and observed salinity_

- [ ] incorporate into Muk alk vs salinity curve
- [ ] Paul review data

**Comment by michaelmaher114** [comment]
Mike double checked the samples.  Our records show we shipped **8** samples dated **5/21/2018**, but we may have only received data for 5 bottles.  Otherwise the lists check out.

**Comment by pmcelhany** [comment]
@michaelmaher114 What is the complete sample ID for the missing samples?

**Comment by michaelmaher114** [comment]
We say we sent 8 samples.  We got these 5 back: 5-21-18 CH01, 5-21-18 CH02, 5-21-18 CH08, 5-21-18 CH09, 5-21-18 CH10.

I am not sure if I have more information on the bottles we say we sent but will look.  I will email Genevieve

**Comment by pmcelhany** [comment]
@dmperez89 @dmperez89  @michaelmaher114  Please add data to [this table](https://github.com/NWFSC-OA-lab/alk_dic/blob/main/data/milford_run_muk_samples_2021_05_19/milford_run_samples_insitu_data.csv) about the samples run at milford. We need to match the sample with an experiment and any other chemistry data we have related to them. To added the data, clone the repository with github desktop and follow the directions for pushing and pulling in Appendix E of the [lab guide](https://docs.google.com/document/d/1jgpHNdL_pTERZEX3EAcj9mIiySXnBb6J_orueZVwkXs/edit). Add metadata with the metacsv package.

**Comment by michaelmaher114** [comment]
For "Match results with experiment/pH/temp/salinity" - I think we already figured out what experiments go with what samples.  Mike has the list

**Comment by KROVINSKI** [comment]
I've pushed comments for each bottle for what project they were associated. I can't reconcile 9-8-16 M4 and it seems we only have 2 of 9 bottles for the pteropods. 
Questions remaining: 
durafet_pH - simple for smaller duration studies but what should we do about ambient treatment over the course of the year? What should we do about Day and Night pHs? Does it only matter for when the sample was taken? Example- if sample taken in the night period for krill is that the pH value that should be   @pmcelhany @michaelmaher114 
SPEC_pH - same questions above
chamber_co2 - do we want atmospheres? what's the units?
temperature - day/ night differences
salinity - salinity varied in all studies except for short 1-2 month studies. (is it only important for when the sample was taken)

**Comment by pmcelhany** [comment]
Review if we need these data...
