### ISSUE TITLE
Formalin storage and preservation location

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#15]
- [ ] Ask Ali about how to store
- [ ] NOt in pilopt pant
- [ ] In 342 or225?
- [ ]

**Comment by pmcelhany** [comment]
@KROVINSKI @dmperez89 @michaelmaher114 
Can we mark this as done?

**Comment by KROVINSKI** [comment]
Let me see how many vials were still have under the hood in 342. But @dmperez89 did we get the okay to store in that annex cabinet or did it just fit there?

**Comment by dmperez89** [comment]
@KROVINSKI I don't think anyone ever told us we could...but they also didn't tell us we couldn't.

**Comment by pmcelhany** [comment]
solved
