### ISSUE TITLE
Write SOP for titrator acid

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#18]
- [ ] Write SOP for titrator acid

**Comment by dmperez89** [comment]
Ongoing SOP added [here](https://docs.google.com/document/d/1RhqbY3nerG9RUdHxqfDW8oSMpsnXvsT2xeybTyla_Rk/edit)

Ocean Acidification Drive -> 03. OA Systems, Experiment Chemistry, & Equipment -> 01. SOPs -> 01. Water Chemistry SOPs -> Making acid for the titrator

**Comment by pmcelhany** [comment]
Done enough
