### ISSUE TITLE
Titrator pH probe

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#22]
- [ ] Get 3M KCl to replenish pH probe electrolyte

**Comment by pmcelhany** [comment]
@michaelmaher114 @dmperez89 @KROVINSKI Did the KCl arrive yesterday?

**Comment by dmperez89** [comment]
Last I heard it was delayed and supposed to arrive today.

**Comment by michaelmaher114** [comment]
Yeah it is supposed to arrive today.

Mike

**Comment by pmcelhany** [comment]
Probe is OK, we now have a backup
