### ISSUE TITLE
Titrator pH probe storage solution

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#24]
- [ ] Order storage solution

**Comment by pmcelhany** [comment]
@dmperez89 @michaelmaher114 
I assume we have the solution and I can close this issue?

**Comment by dmperez89** [comment]
@pmcelhany @michaelmaher114 yes, I believe this lives in 342 now.

**Comment by pmcelhany** [comment]
We have the solution

**Comment by michaelmaher114** [comment]
Actually I am not sure we do....

**Comment by dmperez89** [comment]
This is what we have three small bottles of. But now I can’t remember if
this is for inside the probe or inside the storage holder.

**Comment by michaelmaher114** [comment]
I know I was confused as well.  I actually think the storage solution,
which is slightly different from the probe filler solution, is finally
being delivered soon however.

**Comment by pmcelhany** [comment]
order some, on its way

**Comment by pmcelhany** [comment]
done!
