### ISSUE TITLE
Cleaning DIC sample bottles

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#3]
- [x] @pmcelhany look for sop from simone
- [x] Review [email from PMEL](https://drive.google.com/file/d/16BUeL9VJSQUXCCgNlrjTzpAv7dn_yOsR/view?usp=sharing) on bottle cleaning
- [x] Review/write our labs cleaning SOP (add link to SOP to this issue thread)
- [ ] Draft SOP for HgCl2 and seawater disposal for review by Ali (Danielle)
- [ ] Get our lab SOP reviewed by PMEL (we should get them to check that what we plan is consistent with current best practice)
- [ ] Review/write SOP for dealing with HgCl2 waste (add link to SOP to this issue thread) (Danielle)
- [ ] **ID location for cleaning and get detergent (liquinox??)** (ordered gsa)
- [x] get muffle oven from sandpoint
- [x] **Find ( or buy) gloves for oven** (ordered gsa)
- [x] check with piper about bat cave location for oven
- [x] Test muffle oven
- [ ] First first test of SOP on sample bottles returned from Milford
- [ ] Find/buy haz waste jugs and secondary containment

**Comment by pmcelhany** [comment]
I added a link to an [email chain with PMEL](https://drive.google.com/file/d/16BUeL9VJSQUXCCgNlrjTzpAv7dn_yOsR/view?usp=sharing) on bottle cleaning

**Comment by dmperez89** [comment]
I wrote up a very short [SOP](https://docs.google.com/document/d/1DEqJ8mWNvbktSRJoee7YCl97ymyvMp3HQQRKsv6xe3M/edit) based on the email thread. It lives on the new drive: Ocean Acidification Drive --> 03. OA Systems, Experiment Chemistry, and Equipment --> 01. SOPs --> DIC Bottle Cleaning

**Comment by michaelmaher114** [comment]
I just checked and the oven down by the bat cave is not the muffle over we are thinking of.  The oven that is down there only goes to 150-200 deg C. 

Now I think I remember that we moved our muffle oven up to Muk.  I think it is probably in one of our storage boxes at Sand Point.

**Comment by pmcelhany** [comment]
I think you are right, we did move it to Muk and now in a container. Are
the connections to set up the oven by the bat cave still there?
-paul

**Comment by michaelmaher114** [comment]
Yes the electrical connection is still there.  Looks like Piper has another smaller instrument there too right now, but there is also some room.

**Comment by pmcelhany** [comment]
Does it require a vent?

**Comment by michaelmaher114** [comment]
Does the oven require a vent?  I don't think it does.  At least nothing like a vent to outside the room it is in.

**Comment by pmcelhany** [comment]
I don't remember. Maybe it just needs a 208/240V circuit.
-paul
