### ISSUE TITLE
Bring Alex's titrator online

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#4]
- [x] precision test (10 test of same batch of IO)
- [x] titrator training
- [x] CRM test
- [x] bottles for titration seawater
- [ ] Hardwire computer to NWFSC guest (contact IT Danielle)

**Comment by pmcelhany** [comment]
Do we need an SOP for new titration acid?

**Comment by pmcelhany** [comment]
@michaelmaher114 What are the next steps for working with the new titrator acid?

**Comment by michaelmaher114** [comment]
We need to run titrations with the water bath in operation.  Once we get a repeatable level of precision we can run standards and figure out the acid concentration.

**Comment by pmcelhany** [comment]
The Jubalo water bath is now up in 342e, so we can use that one for now.

**Comment by dmperez89** [comment]
@pmcelhany @michaelmaher114 @KROVINSKI  assuming the titration bottles are the ones Kate and I cleaned, we should have plenty for now. Do we still want to look into connecting that computer to the internet? If it's UW's, I'm not sure how they'd feel about it, and while it's a little cumbersome, I think it's been working to have a secondary laptop for the most part.

**Comment by pmcelhany** [comment]
It seems to be working!

**Comment by pmcelhany** [comment]
@dmperez89 If we have a usb wifi, we can just connect alex's computer to the nwfsc public wifi. I'll check with IT about buying one.

**Comment by pmcelhany** [comment]
Titrator operational
