### ISSUE TITLE
buy water water bath

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#5]
- [x] Buy [thermoelectric water bath](https://www.thermotekusa.com/product.php?pid=108)
- [x ] borrowed water bath from Chase

**Comment by michaelmaher114** [comment]
adding the link to the water bath research spread sheet

https://docs.google.com/spreadsheets/d/1J9TqGcWIC6ClYhHLgIpHYeZpHNVIlPU7/edit#gid=1394857263
