### ISSUE TITLE
Chemical inventory and labeling

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#7]
Inventory Due March 11

- [x] Complete OA lab chemical inventory update...
- [x] Update/review chemical labels in the lab
- [ ] SOPs on chemical use
- [x] Find out about new inventory system (RSS) (Kate follow up with Ali) (no response from Ali- check the 7 training videos) [HERE](https://drive.google.com/drive/folders/1Q9xj3pEHx31xhJA2hAfZi8EeCb8skvXy?usp=sharing)
- [x] Paul log in to RSS (https://homeport.northwestscience.fisheries.noaa.gov/safety/Industrial_Safety_and_Health/transition.cfm) or link [HERE](https://homeport.northwestscience.fisheries.noaa.gov/safety/Industrial_Safety_and_Health/transition.cfm)
- [x] google meet with Ali
- [ ] Enter OA lab chemicals (check the inventory at [https://app.riskandsafety.com/](url) )
- [ ] Physical check of inventory (once we get back in the lab)
- [ ] Walk through with Ali (Kate or Danielle set this up [ on hold RTOW])

**Comment by dmperez89** [comment]
@pmcelhany @KROVINSKI @michaelmaher114 
I drafted some chemical SOPs and put them on the [drive](https://drive.google.com/drive/folders/1dL7tYxmL2AvCDWfSu2w4hjnD3aVSV7K1?usp=sharing). Let me know what you think of that layout and if there are chemicals I'm missing.

**Comment by pmcelhany** [comment]
chemicals up to date in database
