### ISSUE TITLE
Chemical waste/process SOPs

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#8]
Chemical SOP are [here](https://drive.google.com/drive/folders/1dL7tYxmL2AvCDWfSu2w4hjnD3aVSV7K1?usp=sharing)

- [ ] Mike and Danielle meet on sops
- [ ] Submit SOPs to Ali
- [ ] Find out about pH range down the sink? Buffering?

**Comment by pmcelhany** [comment]
@dmperez89 What is the status of this?

**Comment by dmperez89** [comment]
@pmcelhany @KROVINSKI @michaelmaher114 awhile back I made a bunch of SOPs and put them [here](https://drive.google.com/drive/folders/1dL7tYxmL2AvCDWfSu2w4hjnD3aVSV7K1?usp=sharing) but I haven't looked at them recently. As far as I know we got the ok to dispose of titration waste down the sink.

**Comment by michaelmaher114** [comment]
Yeah we can put the titrated seawater (with acid) down the sink.  We can
put the mercuric chloride samples in the waste jug for removal by Ali.

I guess we can include this information in the titration SOP we worked on
last week.

**Comment by pmcelhany** [comment]
complete
